export const apiRoutes = {
    GET_CLIENTS: 'user/getClients.php',
    GET_USERS: 'user/getUser.php',
    REGISTER_USER: 'user/register.php',
    LOGIN_USER: 'auth/login.php',
    LOGOUT_USER: 'auth/logout.php',
    UPDATE_USER: 'user/updateUser.php',
    DELETE_USER: 'user/deleteUser.php',
    CHANGE_PASSWORD: '/user/changePassword.php',
    FORGOT_PASSWORD: '/user/forgotPassword.php',
    RESET_PASSWORD: '/user/resetPassword.php',
    INSERT_SERVICE: 'service/insertService.php',
    GET_USER_SERVICES: 'service/getUserServices.php',
    GET_ALL_SERVICES: 'service/getAllServices.php',
    DELETE_SERVICE: 'service/deleteService.php',
    UPDATE_SERVICE: 'service/updateService.php',
    INSERT_APPOINTMENT: 'appointment/insertAppointment.php',
    GET_RESERVED_AND_BARBER_APPOINTMENTS: 'appointment/getReservedAndBarberAppointments.php',
    GET_APPOINTMENT_DATES_BY_RANGE: 'appointment/getAppointmentDatesByRange.php',
    GET_CLIENT_APPOINTMENTS: 'appointment/getClientAppointments.php',
    DELETE_CLIENT_APPOINTMENT: 'appointment/deleteClientAppointment.php',
    GET_WORKING_HOURS_BY_USER_ID: 'working_hours/getWorkingHoursByUserId.php',
    GET_WORKING_HOURS_FOR_DATE: 'working_hours/getWorkingHoursForDate.php',
    DELETE_WORKING_HOURS_BY_ID:'working_hours/deleteWorkingHours.php',
    INSERT_WORKING_HOURS: 'working_hours/insertWorkingHours.php',
    UPDATE_WORKING_HOURS: 'working_hours/updateWorkingHours.php',
    GET_RESERVED_DATES: 'reserved_dates/getReservedDates.php'

} as const;
export type ApiRoute = typeof apiRoutes[keyof typeof apiRoutes];